const BUSINESS_STATUSES = Object.freeze({
    OPEN: "OPERATIONAL",
    CLOSED_TEMP: "CLOSED_TEMPORARILY", 
    CLOSED_PERM: "CLOSED_PERMANENTLY"
})

const BUSINESS_STATUS_VALUES = Object.freeze(Object.values(BUSINESS_STATUSES))

module.exports = {
    BUSINESS_STATUSES,
    BUSINESS_STATUS_VALUES
}